                entry % Start here
                addi  r2,r0,10
                sw    test(r0),r2 % generated by line 23
                addi  r2,r0,33
                sw    test2(r0),r2 % generated by line 24
                addi  r2,r0,12
                sw    test(r0),r2 % generated by line 25
                hlt   % Stop here
comp            res 64
results         res 400
test            res 4
test2           res 4
