                entry % Start here
main            align
                addi  r2,r0,10
                sw    test(r0),r2 % generated by line 23
                addi  r2,r0,33
                sw    test2(r0),r2 % generated by line 24
                addi  r2,r0,12
                sw    test(r0),r2 % generated by line 25
                lw    r1,test2(r0)
                jl    r15,putint
                addi  r1,r0,23413
                jl    r15,putint
                hlt   % Stop here
Compiler_test   align
t               res 4
                addi  r2,r0,t(r0)
                sw    tested(r0),r2 % generated by line 16
comp            res 64
results         res 400
test            res 4
test2           res 4
