                entry % Start here
main            align
                addi  r2,r0,10
                sw    myint(r0),r2 % generated by line 17
                lw    r1,myint(r0)
                jl    r15,putint
                hlt   % Stop here
a               res 4
b               res 4
c               res 4
Crusher_crush   align
                lw    r2,a(r0)
                lw    r2,b(r0)
                sw    c(r0),r2 % generated by line 7
                jr    r14
toBePrinted     res 4
print           align
                lw    r1,toBePrinted(r0)
                jl    r15,putint
                jr    r14
myint           res 4
crusher         res 16
