                entry % Start here
main            align
                addi  r2,r0,0
                sw    b(r0),r2 % generated by line 2
                addi  r2,r0,1
                sw    i(r0),r2
sfor0           align
                lw    r2,i(r0)
                addi  r3,r0,10
                cle   r4,r2,r3
                bz    r4,endfor0
                addi  r2,r0,1
                sw    y(r0),r2
sfor1           align
                lw    r2,y(r0)
                addi  r3,r0,10
                cle   r4,r2,r3
                bz    r4,endfor1
                lw    r3,i(r0)
                lw    r4,y(r0)
                add   r2,r3,r4
                sw    b(r0),r2 % generated by line 5
                lw    r1,b(r0)
                jl    r15,putint
                addi  r1,r0,10
                putc  r1
                lw    r3,y(r0)
                addi  r4,r0,1
                add   r2,r3,r4
                sw    y(r0),r2
                j     sfor1
endfor1         align
                lw    r3,i(r0)
                addi  r4,r0,1
                add   r2,r3,r4
                sw    i(r0),r2
                j     sfor0
endfor0         align
                addi  r3,r0,5
                addi  r6,r0,6
                addi  r7,r0,12
                add   r5,r6,r7
                addi  r6,r0,9
                div   r4,r5,r6
                mul   r2,r3,r4
                sw    a(r0),r2 % generated by line 10
                lw    r1,a(r0)
                jl    r15,putint
                addi  r1,r0,10
                putc  r1
                hlt   % Stop here
b               res   4
a               res   4
i               res   4
y               res   4
