                entry % Start here
main            align
                addi  r2,r0,10
                sw    myint(r0),r2 % generated by line 17
if0             align
                lw    r2,myint(r0)
                addi  r3,r0,10
                cle   r4,r2,r3
                bz    r4,else0
                lw    r1,myint(r0)
                jl    r15,putint
                addi  r1,r0,10
                putc  r1
if1             align
                addi  r2,r0,12
                addi  r3,r0,0
                clt   r4,r2,r3
                bz    r4,else1
                addi  r1,r0,12
                jl    r15,putint
                addi  r1,r0,10
                putc  r1
                j     aftif1
else1           align
                addi  r1,r0,0
                jl    r15,putint
                addi  r1,r0,10
                putc  r1
aftif1          align
                j     aftif0
else0           align
                addi  r2,r0,12
                sw    toBePrinted(r0),r2
                jl    r14,print
aftif0          align
                hlt   % Stop here
a               res   4
b               res   4
c               res   4
Crusher_crush   align
                lw    r2,a(r0)
                lw    r2,b(r0)
                sw    c(r0),r2 % generated by line 7
                jr    r14
toBePrinted     res   4
print           align
                lw    r1,toBePrinted(r0)
                jl    r15,putint
                addi  r1,r0,10
                putc  r1
                jr    r14
myint           res   4
crusher         res   16
